server:
  port: 4002
spring:
  mail:
    host: smtp.163.com
    username: javatestyukiice@163.com
    password: IXQADHCOAZKVCVTX
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver