server:
  port: 4006
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456789

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #???????resultType?????
  type-aliases-package: com.yukiice.mybatisreview.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl